version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build
    steps:
      - checkout
      - restore_cache: 
          name: Restore Cache Dependencies
          key: myapp-{{ checksum "./server/stack.yaml" }}-{{ checksum "./server/package.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: cd server && stack setup
      - run:
          name: Build
          command: cd server && stack build
      - save_cache: 
          name: Cache Dependencies
          key: myapp-{{ checksum "./server/stack.yaml" }}-{{ checksum "./server/package.cabal" }}
          paths: 
            - "/root/.stack"
            - "./server/.stack-work"

