name: Server 

on: [push]

jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 

      - name: Checkout repo 
        uses: actions/checkout@v2 

      - name: Cache Dependencies 
        uses: actions/cache@v2 
        with: 
          path: ~/.stack
          key: my-app-${{ hashFiles('server/stack.yaml') }}-${{ hashFiles('server/package.yaml') }}

      - name: Build Server 
        run: cd server && stack build 
        
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: "server"
          buildpack: "https://github.com/mfine/heroku-buildpack-stack"
          branch: "servant"

